-- HorseProno V3 production schema for Supabase/PostgreSQL.
create extension if not exists pgcrypto;

create table if not exists races (
  race_id text primary key,
  race_date date not null,
  start_time timestamptz,
  reunion int,
  course_number int,
  discipline text not null default 'INCONNU',
  hippodrome text not null default 'INCONNU',
  distance int,
  terrain text,
  field_size int,
  source text not null default 'unknown',
  source_url text,
  status text not null default 'unknown',
  updated_at timestamptz not null default now()
);

create table if not exists participants (
  race_id text not null references races(race_id) on delete cascade,
  horse_number int not null,
  horse_name text not null,
  horse_id text,
  jockey text,
  jockey_id text,
  trainer text,
  trainer_id text,
  odds numeric,
  draw int,
  weight numeric,
  recent_form text,
  finish_position int,
  disqualified boolean default false,
  non_runner boolean default false,
  raw_payload jsonb,
  updated_at timestamptz not null default now(),
  primary key (race_id, horse_number)
);

create index if not exists idx_participants_horse on participants(horse_name);
create index if not exists idx_participants_jockey on participants(jockey);
create index if not exists idx_participants_trainer on participants(trainer);
create index if not exists idx_participants_finish on participants(finish_position);

create table if not exists market_snapshots (
  id bigint generated by default as identity primary key,
  race_id text not null references races(race_id) on delete cascade,
  captured_at timestamptz not null default now(),
  horse_number int not null,
  odds numeric,
  source text not null default 'unknown'
);
create index if not exists idx_market_snapshots_race on market_snapshots(race_id, captured_at desc);

create table if not exists ingestion_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  status text not null,
  window_start date,
  window_end date,
  rows_read int not null default 0,
  rows_written int not null default 0,
  message text
);

create table if not exists model_versions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  model_name text not null,
  model_type text not null,
  feature_columns jsonb not null,
  artifact jsonb not null,
  metrics jsonb not null default '{}'::jsonb,
  training_snapshot text,
  artifact_hash text not null unique,
  is_active boolean not null default false
);
create index if not exists idx_model_versions_active on model_versions(is_active, created_at desc);

create table if not exists backtest_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  model_version_id bigint references model_versions(id),
  period_start date,
  period_end date,
  races int,
  metrics jsonb not null default '{}'::jsonb
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  race_id text not null references races(race_id) on delete cascade,
  model_version_id bigint references model_versions(id),
  horse_number int not null,
  win_probability numeric not null,
  place_probability numeric not null,
  market_probability numeric,
  expected_value numeric,
  rank int not null,
  recommendation text,
  explanation text
);
create index if not exists idx_predictions_race on predictions(race_id, created_at desc);

-- Historical rows before p_race_date. Used to build strictly pre-race features.
create or replace function get_training_history_until(p_race_date date, p_limit int default 200000)
returns table (
  race_id text, race_date date, discipline text, hippodrome text, distance int,
  terrain text, field_size int, horse_number int, horse_name text, jockey text,
  trainer text, odds numeric, draw int, weight numeric, recent_form text,
  finish_position int
)
language sql stable as $$
  select p.race_id, r.race_date, r.discipline, r.hippodrome, r.distance,
         r.terrain, r.field_size, p.horse_number, p.horse_name, p.jockey,
         p.trainer, p.odds, p.draw, p.weight, p.recent_form, p.finish_position
  from participants p
  join races r on r.race_id = p.race_id
  where r.race_date < p_race_date
    and p.finish_position is not null
    and coalesce(p.non_runner, false) = false
  order by r.race_date asc, p.race_id asc, p.horse_number asc
  limit p_limit;
$$;

-- Read policies for the public app. ETL writes use a service-role key outside the app.
alter table races enable row level security;
alter table participants enable row level security;
alter table market_snapshots enable row level security;
alter table model_versions enable row level security;
alter table predictions enable row level security;

create policy "public read races" on races for select using (true);
create policy "public read participants" on participants for select using (true);
create policy "public read market snapshots" on market_snapshots for select using (true);
create policy "public read active models" on model_versions for select using (is_active = true);
create policy "public read predictions" on predictions for select using (true);
