-- HorseProno V3 production schema for Supabase/PostgreSQL.
create extension if not exists pgcrypto;

create table if not exists races (
  id bigint generated by default as identity primary key,
  external_id text unique,
  race_date date not null,
  start_time timestamptz,
  meeting_number int,
  race_number int not null,
  discipline text,
  hippodrome text,
  distance_m int,
  terrain text,
  field_size int,
  status text default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists participants (
  id bigint generated by default as identity primary key,
  race_id bigint not null references races(id) on delete cascade,
  external_id text,
  horse_name text not null,
  horse_number int,
  jockey_name text,
  trainer_name text,
  odds numeric,
  weight_kg numeric,
  draw int,
  age int,
  sex text,
  recent_form text,
  finish_position int,
  is_non_runner boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_participants_horse on participants(horse_name);
create index if not exists idx_participants_jockey on participants(jockey_name);
create index if not exists idx_participants_trainer on participants(trainer_name);
create index if not exists idx_participants_finish on participants(finish_position);

create table if not exists market_snapshots (
  id bigint generated by default as identity primary key,
  race_id text not null references races(race_id) on delete cascade,
  captured_at timestamptz not null default now(),
  horse_number int not null,
  odds numeric,
  source text not null default 'unknown'
);
create index if not exists idx_market_snapshots_race on market_snapshots(race_id, captured_at desc);

create table if not exists ingestion_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  status text not null,
  window_start date,
  window_end date,
  rows_read int not null default 0,
  rows_written int not null default 0,
  message text
);

create table if not exists model_versions (
  id bigint generated by default as identity primary key,
  model_name text not null,
  model_type text not null,
  trained_at timestamptz not null default now(),
  training_rows int,
  metrics jsonb not null default '{}'::jsonb,
  features jsonb not null default '[]'::jsonb,
  artifact jsonb not null,
  artifact_hash text,
  is_active boolean not null default false
);

create table if not exists backtest_runs (
  id bigint generated by default as identity primary key,
  model_version_id bigint references model_versions(id),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  notes text
);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  race_id bigint not null references races(id) on delete cascade,
  participant_id bigint not null references participants(id) on delete cascade,
  model_version_id bigint references model_versions(id),
  predicted_at timestamptz not null default now(),
  win_probability numeric,
  place_probability numeric,
  expected_value numeric,
  rank int
);

create index if not exists idx_model_versions_active_trained_at on model_versions(is_active, trained_at desc);
create index if not exists idx_predictions_race on predictions(race_id, predicted_at desc);

-- Historical rows before p_race_date. Used to build strictly pre-race features.
create or replace function get_training_history_until(p_race_date date, p_limit int default 200000)
returns table (
  race_id text, race_date date, discipline text, hippodrome text, distance int,
  terrain text, field_size int, horse_number int, horse_name text, jockey text,
  trainer text, odds numeric, draw int, weight numeric, recent_form text,
  finish_position int
)
language sql stable as $$
  select r.external_id::text, r.race_date, r.discipline, r.hippodrome, r.distance_m,
         r.terrain, r.field_size, p.horse_number, p.horse_name, p.jockey_name,
         p.trainer_name, p.odds, p.draw, p.weight_kg, p.recent_form, p.finish_position
  from participants p join races r on r.id = p.race_id
  where r.race_date < p_race_date
    and p.finish_position is not null
    and coalesce(p.is_non_runner,false)=false
  order by r.race_date asc, r.external_id asc, p.horse_number asc
  limit p_limit;
$$;

-- Read policies for the public app. ETL writes use a service-role key outside the app.
alter table races enable row level security;
alter table participants enable row level security;
alter table market_snapshots enable row level security;
alter table model_versions enable row level security;
alter table predictions enable row level security;

create policy "public read races" on races for select using (true);
create policy "public read participants" on participants for select using (true);
create policy "public read market snapshots" on market_snapshots for select using (true);
create policy "public read active models" on model_versions for select using (is_active = true);
create policy "public read predictions" on predictions for select using (true);
