-- HorseProno production schema for Supabase/PostgreSQL.
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists races (
  race_id text primary key,
  race_date date not null,
  reunion int,
  course_number int,
  discipline text not null default 'INCONNU',
  hippodrome text not null default 'INCONNU',
  distance int,
  terrain text,
  field_size int,
  source text not null default 'unknown',
  source_url text,
  updated_at timestamptz not null default now()
);

create table if not exists participants (
  race_id text not null references races(race_id) on delete cascade,
  horse_number int not null,
  horse_name text not null,
  jockey text,
  trainer text,
  odds numeric,
  draw int,
  weight numeric,
  recent_form text,
  career_runs int,
  career_wins int,
  career_places int,
  finish_position int,
  raw_payload jsonb,
  updated_at timestamptz not null default now(),
  primary key (race_id, horse_number)
);

create table if not exists ingestion_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null,
  status text not null,
  rows_read int not null default 0,
  rows_written int not null default 0,
  message text
);

create table if not exists model_versions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  model_name text not null,
  model_type text not null,
  feature_columns jsonb not null,
  artifact jsonb not null,
  metrics jsonb not null default '{}'::jsonb,
  artifact_hash text not null,
  is_active boolean not null default false
);

create unique index if not exists ux_model_versions_hash on model_versions(artifact_hash);
create index if not exists idx_model_versions_active on model_versions(is_active, created_at desc);
create index if not exists idx_participants_finish on participants(finish_position);
create index if not exists idx_races_date on races(race_date desc);

create table if not exists predictions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  race_id text not null references races(race_id) on delete cascade,
  model_version_id bigint references model_versions(id),
  horse_number int not null,
  win_probability numeric not null,
  place_probability numeric not null,
  rank int not null,
  explanation text
);

create index if not exists idx_predictions_race on predictions(race_id, created_at desc);

-- Public read access can be enabled for a public read-only app.
-- Write access should normally be restricted to trusted ETL/service jobs.
alter table races enable row level security;
alter table participants enable row level security;
alter table model_versions enable row level security;
alter table predictions enable row level security;

create policy "public read races" on races for select using (true);
create policy "public read participants" on participants for select using (true);
create policy "public read active models" on model_versions for select using (is_active = true);
create policy "public read predictions" on predictions for select using (true);

-- ETL writes should use a service-role key outside the public app.
-- Do not create broad public INSERT/UPDATE policies for production.
